# Information about students realized through dictionary

data = {
    1: {
        "name": "Ivan",
        "surname": "Beliy",
        "patronymic": "Aleksandrovich",
        "course": 1,
        "birth_year": 2000,
        "group_number": "321-1",
        "grades": {
            "math": 3,
            "electrical_circuit": 4,
            "digital_signal_processing": 4,
            "fpga_programming": 5,
            "physics": 4,
        },
    },
    2: {
        "name": "Andrey",
        "surname": "Chernuy",
        "patronymic": "Vladimirovich",
        "course": 2,
        "birth_year": 1997,
        "group_number": "201",
        "grades": {
            "math": 3,
            "electrical_circuit": 4,
            "digital_signal_processing": 2,
            "fpga_programming": 4,
            "physics": 3,
        },
    },
    3: {
        "name": "Vasiliy",
        "surname": "Terkin",
        "patronymic": "Timofeevich",
        "course": 3,
        "birth_year": 2002,
        "group_number": "521",
        "grades": {
            "math": 5,
            "electrical_circuit": 5,
            "digital_signal_processing": 5,
            "fpga_programming": 4,
            "physics": 3,
        },
    },
    4: {
        "name": "Evgeniy",
        "surname": "Akimov",
        "patronymic": "Petrovich",
        "course": 1,
        "birth_year": 1998,
        "group_number": "321-1",
        "grades": {
            "math": 5,
            "electrical_circuit": 4,
            "digital_signal_processing": 4,
            "fpga_programming": 5,
            "physics": 5,
        },
    },
    5: {
        "name": "Alina",
        "surname": "Koshkina",
        "patronymic": "Aleksandrova",
        "course": 2,
        "birth_year": 2001,
        "group_number": "521",
        "grades": {
            "math": 5,
            "electrical_circuit": 5,
            "digital_signal_processing": 5,
            "fpga_programming": 5,
            "physics": 5,
        },
    },
    6: {
        "name": "Timofey",
        "surname": "Kishenev",
        "patronymic": "Olegovich",
        "course": 3,
        "birth_year": 1997,
        "group_number": "201",
        "grades": {
            "math": 3,
            "electrical_circuit": 5,
            "digital_signal_processing": 3,
            "fpga_programming": 4,
            "physics": 3,
        },
    },
}
